
using com.unisys.rms.domain;
using com.unisys.rms.domain.criteria;





///<p>Task related entities</p>
// @generated
namespace com.unisys.rms.domain.task
{

	
	///<p >Represents a preference in the allocation of a Task to a Resource. Preferences are generated by evaluating Preference Rules. One preference will be generated by one Rule.</p><p >Preferences are contained in Tasks and do not have any independent existence.</p>
	// @wasgenerated
	public partial class Preference : RMSEntity
	{


		// @generated
		private Rule rule;



		// @generated
		private Task task;



		///<p>The rule that generated this preference. Only preference rules are allowed</p>
		// @generated
		public Rule Rule
		{

			get
			{
				return rule;
			}

			set
			{
				SetField(ref rule, value, () => Rule);
			}

		}


	

		///<p>The Task to which this preference belongs</p>
		// @generated
		public Task Task
		{

			get
			{
				return task;
			}

			set
			{
				SetField(ref task, value, () => Task);
			}

		}



	
	}
	

}



